<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
	<!ELEMENT students (student+)>
	<!ELEMENT student (name,age,gender)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT gender (#PCDATA)>
	]>
<students>
	<student>
		<name>章三</name>
		<age>20</age>
		<gender>男</gender>
	 </student>
	 <student>
		<name>李四</name>
		<age>21</age>
		<gender>男</gender>
	 </student>
</students>